# Generated by Django 5.1.7 on 2025-03-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_track', '0003_remove_expense_category_remove_expense_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
